package-lock.json
package.json
src/components/Recos.jsx
src/components/SocialImage.jsx
src/pages/index.astro

This PR connects api.opensauced.pizza to the open graph UI.

Feat: trying to do this with next-alpha build

---

.github/workflows/compliance.yml

This PR adds compliance workflow to raise the bar on contributions.

feat: Adds compliance.yml

---

src/components/LayoutToggle.jsx
src/components/PostGrid.jsx
src/components/PostList.jsx
src/components/PostsWrap.jsx

This PR fixes the bug regarding the title name of each card redirecting the users to the respective GitHub repository linked to the name
This commit shows there are changes on 4 files but in the real sense I only worked on one. The other changes were due to the fact that I was looking through each file and my Prettier settings adjusted the code but didn't delete anything asides from excess whitespace. The code I added is found in the PostGrid.jsx file and the title name response as suggested in the PR description above
Fixes #22

fix: Linked title to its respective github page

---

src/components/PostGrid.jsx
src/components/PostList.jsx
src/lib/getAvatar.js
src/lib/getAvatar.test.js

This PR replaces the static avatars with the avatars of the contributors listed in the `contributors` array coming from the API
Fixes #21 
Changes reflected on both the list and grid view
N/A

feat: replace placeholder avatars with contributor avatars

---

.github/workflows/development.yml
.github/workflows/release.yml

This PR adds better development workflows, a-la opensauced.pizza
closes #31

ci: adopt reusable open-sauced development workflows

---

.github/workflows/release.yml

This PR attempts to make the diagram artifact download conditional for the times it silently fails.
fixes #31

ci: make diagram download optional as it can apparently fail

---

src/components/PostGrid.jsx
src/components/PostList.jsx
src/data/posts.json

This PR add more data to the static json
1. Add contributor data
2. Update the API to be leverage instead of static file

feat: updates static json to include more content

---

src/pages/index.astro

This PR adds the social card to meta tags. 
https://github.com/open-sauced/open-sauced/pull/1348
closes #35

feat: adds social card

---

.github/workflows/release.yml
public/robots.txt

This PR fixes the release build and social card preview.

fix: robots.txt and release

---

src/pages/index.astro

This PR replaces the title and description of the site.

fix: title and description

---

src/components/PostList.jsx

- [x ] ✨ Feature
issue #54
I changed the icon and tested it on stackblitz before committing the changes. it works
This PR fixes the feature 
Fixes #54 
https://github.com/open-sauced/hot/issues/54#issuecomment-1003669786
- [ x] 🙅 no, because they aren't needed
- [x ] 🙅 no documentation needed

fix: Replaced the discussion svg with the github issue one

---

src/components/PostList.jsx

This PR fixes the font size for the issue svg, so it could match the size of the other svgs (stars and comments). Additionally, I noticed that the number of issues was hard coded to the number 5. Not sure if this was done purposely, but I changed it to pull the actual number of issues per project. 
Fixes #58 
**Before:**
**After:**

fix: unusal size of svg icon and issue number hardcoded

---

src/components/PostList.jsx

This PR fixes the duplicated issue data and SVG bug. 
Fixes #65

fix: fixes wrong svg and data

---

src/components/GridDisplay.jsx
src/components/ListDisplay.jsx
src/components/PostList.jsx

This PR fixes the placement of the action buttons in the post list toggled view. It makes the buttons align together across the whole card
Fixes #61

fix: adjusting post list view action buttons

---

npm-shrinkwrap.json
package.json
src/components/PostGrid.jsx
src/components/PostList.jsx
src/lib/database.js

This PR adds a connection to the supabase votes column in the recommendation in order to make live updates. 
fixes #12 
1. Implement supabase studio https://github.com/open-sauced/hot/issues/68
2. Make a decision on Context API vs local storage - https://github.com/open-sauced/hot/issues/38

feat: Implement voting logic

---

src/components/HotHead.astro

This PR updates the title for SEO. Hot & Ready
n/a

fix: updates title again "Hot & Ready"

---

.github/workflows/release.yml
.gitignore
Dockerfile

This PR finishes the work started in #72 
Fixes #70 in GitHub actions

ci: implement variable overload for release workflow

---

src/components/GridDisplay.jsx
src/components/ListDisplay.jsx
src/components/PostsWrap.jsx
src/lib/database.js

This PR adds the Upvoted filter. 
This PR will also indirectly Fixes #64 
None
Tests weren't added because the testing strategy has not been defined.
While working on this I noticed that the recommendation table may contain more than one row for a particular repository. There may need to be some data cleanup on the table to remove the duplicates.

feat: implemented upvoted filter

---

src/components/PrimaryNav.jsx

This PR adds a GitHub avatar to the logged-in user. 
fixes: #86

feat: Logged in user avatar

---

src/components/GridDisplay.jsx
src/components/PostGrid.jsx
src/components/PostsWrap.jsx

This PR makes the social images that are rendered on each card to be clickable on `PostGrid.jsx` file. Upon clicking the image, you will be redirected to the GitHub repo of that given project 
Fixes #83

feat: PostGrid social image to redirect to repo

---

src/components/Footer.jsx

This PR adds the new footer links

feat: Dev and Youtube added to the footer

---

README.md

This PR improves the dependabot badge in the README. 
Fixes #101

feat: better dependabot badge (readme)

---

src/components/PrimaryNav.jsx

This PR adds  hyperlink to the user name in dropdown menu. 
Closes #111 
https://user-images.githubusercontent.com/70362828/151658907-08600087-69f2-405b-9dc3-7b85ce316627.mp4

feat: Linked to user profile in the user dropdown

---

.github/workflows/release.yml

This PR removes the diagram download condition from previous version.

fix: remove diagram artifact condition

---

src/components/PostsWrap.jsx
src/components/SecondaryNav.jsx
src/lib/database.js

This PR adds the feature #124 Add ability for a user to see the repos they have voted for. 
closes #124
Modified the Secondary Navbar to add the new `MyVotes` link
It's my son's birthday

feat: Add ability for a user to see the repos they have voted for

---

.env
src/hooks/useSupabaseAuth.js

This PR enables login on localhost. 
fixes #108
Perhaps the SITE_URL can be set for Deploy Previews as well....

feat: adds redirect for site_url

---

src/components/GridDisplay.jsx
src/components/ListDisplay.jsx
src/components/PostsWrap.jsx
src/components/SecondaryNav.jsx
src/lib/database.js

This PR adds the ability to fetch more records in lieu of infinite scroll. Infinite scroll is an expensive feature and this is the first step towards that.
#81 
> In Safari when loading more repos the page stayed in its current position but in Chrome and Edge the page scrolled to the bottom of the list. This is more so a difference in how the browsers handle new data being added to the page, but something I noticed.

feat: load more records

---

vite.config.ts

BREAKING CHANGE: removed astro
This PR should fix deploys

feat: correct netlify build and test breaking change

---

.github/workflows/release.yml
netlify.toml
vite.config.ts

This PR adds pre-release channels. 
closes #147
closes #149
- create and push `alpha` and `beta` branches with branch protection: <img width="796" alt="Screenshot 2022-03-12 at 04 47 16" src="https://user-images.githubusercontent.com/237133/158001049-ec4facec-4ca7-4854-ba8a-9162889fe6d6.png">
- implement branch protection settings: <img width="767" alt="Screenshot 2022-03-12 at 04 47 40" src="https://user-images.githubusercontent.com/237133/158001071-fbdc3719-63b0-40ef-97e9-7bec053fd239.png">
- go to Netlify app -> "Build and Deploy" -> "Branches" and enable `beta`
- go to Netlify app -> "Domain Management" -> "Branch subdomains" and select `beta` branch, it will auto-complete the input to `beta.opensauced.pizza`

feat: implement minimal beta release

---

src/lib/supabase.ts

This PR corrects the "loading more" order issue.
closes #129

fix: correct loading of items with normalized order by clause

---

src/components/Avatar.tsx

This PR adds offset to the hover card arrow. 
#141

fix: card offset

---

npm-shrinkwrap.json
package.json
src/App.tsx
src/components/PostGrid.tsx
src/components/PrimaryNav.tsx
src/lib/analytics.ts

This PR [adds] the [feature] using PostHog.

feat: Add posthog to hot sauced project.

---

README.md

This PR should unblock beta deploys.

fix: correct beta releases

---

src/components/PrimaryNav.tsx

This PR fixes the error on @shamimbinnur's branch.

fix: error and adds link to repo

---

src/lib/github.ts

This PR replaces the github links to open sauced links. 
n/a

feat: change repo links

---

src/components/PostGrid.tsx
src/components/PostList.tsx
src/components/PrimaryNav.tsx

This PR fixes #162 (lint errors regarding types and unused variables), and also adds a spinner icon next to repository when searching
#162

feat: correct lint errors + search spinner

---

src/components/Avatar.tsx
src/components/PrimaryNav.tsx
src/components/TextHoverElement.tsx
src/lib/supabase.ts

This PR adds additional features to the search results UI including links to star/view projects and couple of elements present project stars, issues, etc.
Fixes #172

feat: adds new fields to search results

---

index.html

This PR adds more meta tags in hopes that it fixes live in production.

fix(social-card): broken and missing meta tags

---

src/components/PrimaryNav.tsx

I fixed this bug when, just removing that line of code
Closes #222
https://user-images.githubusercontent.com/37635083/180580438-d3413229-d86d-4f34-b69d-c99bc9e06b22.mp4

fix: remove data printed in console log

---

src/components/Modal.tsx
src/components/PrimaryNav.tsx

style: Corrected z-index from user dropdown menu

---

src/components/PrimaryNav.tsx

Fixed issue #236 - Deleted code segment in PrimaryNav.tsx causing an unwanted "My Votes" text. Followed solution instructions and removed lines 83 through 97 from src/components/PrimaryNav.tsx.
Fixes #236

fix: deleted unwanted code segment

---

src/components/PrimaryNav.tsx

after the UI Hero changes, we need to fix merge conflicts and this nav item got re-introduce.

fix(nav-link): remove my votes from primary nav

---

src/components/PrimaryNav.tsx

This Pull request added max-width into the primary nav so as to make it appealing to the eye even on larger screens
Fixes #263

fix: added max width to the primary nav

---

src/components/HotRepositories.tsx

This is a quick change to the hot repo listing. We should eventual make this markable in the DB or automate this in the future, but for now this will be a manual and weekly process.

fix: Update HotRepositories to include tabler/tabler

---

src/components/Hero.tsx

In this PR what I did is just to add shadow to search box from Hero
I used this  class `shadow-2xl` to differentiate between hot repo and search result
Fixes #280

style(hero): added shadow at search box

---

src/components/HotRepositories.tsx
src/components/PostList.tsx

Fixes #279 
i removed the margin-right causing the overlap
Fixes #279

fix: the avatar overlap

---

src/components/Hero.tsx

feat: add contributor avatar in hero search

---

npm-shrinkwrap.json
package.json
src/App.tsx
src/components/RepoSubmission.tsx
src/lib/reactHotToast.ts

This PR adds the flash notification features...
feat  #281 
[https://github.com/open-sauced/hot/issues/281#issue-1326298617](https://github.com/open-sauced/hot/issues/281#issue-1326298617)
after merge notifications will pop up on repo submit as shown below
> desktop error flash message on invalid repo submit
> desktop success flash message on valid repo submit
> mobile error flash message on invalid repo submit
> mobile success flash message on valid repo submit

feat: added system notification

---

.eslintrc.cjs
src/components/HotRepositories.tsx
src/components/PostGrid.tsx
src/components/PostList.tsx
src/lib/handleVoteUpdateByRepo.ts

This PR replaces duplicate codes with a single reusable one.
fixes #271

fix: dedupe handleVoteUpdateByRepo function

---

src/App.tsx
src/components/RepoSubmission.tsx

This PR removes passing down of user from hook

fix: dedupe global user state

---

src/components/PostsWrap.tsx

fixes #302 
[Hot-Open-Sauced-v2-23-1.webm](https://user-images.githubusercontent.com/30659198/184165097-0c834972-b333-407e-a609-2df14cfcf0e9.webm)

fix: load more doesn't load repositories

---

src/hooks/useSWR.ts

So I disabled a repository in the database to see if SWR correctly errors out - turns out, it doesn't and I went leg up forgot to add the issue, or fix it 🍕 
fixes #305

fix: correct swr fetcher not throwing on error

---

src/components/RepoSubmission.tsx

refactor: use outsideclickref instead of query selector

---

src/components/StackedAvatar.tsx

This Pull Request fix #286 issue, In this Pull Request I added white borders to stacked avatars component
fix #286
🤗🤗🎉🎉

feat: Added white borders to Stacked Avatars Component

---

src/components/Hero.tsx

Enables the use of CtrlRight + K and CmdRight + K for the Hero component. 
Fixes #339 . 
https://github.com/open-sauced/hot/issues/339

fix: enables cmd+k and crtl+k from the right side of the keyboard

---

src/components/ListRepositories.tsx

fix: remove anti-pattern from ListRepositories

---

src/components/Hero.tsx

refactor: dry in cmd k handling

---

src/App.tsx
src/components/GridDisplay.tsx
src/components/ListRepositories.tsx
src/components/RepoGrid.tsx
src/components/RepoList.tsx
src/components/RepoWrap.tsx

This PR fixes everything from Post to Repo. 
Fixes #313
https://github.com/open-sauced/hot/issues/313

fix: rename everything from Post to Repo 

---

README.md

fix: trigger build on alpha

---

netlify.toml

fix: alpha build

---

src/App.tsx
src/components/StackedAvatar.tsx

This PR removes the swr local storage provider as it is pretty bugged and incompatible with our current SSR/SSG strategy (we have none)
closes #365

fix: remove swr local storage cache provider

---

src/components/Hero.tsx
src/components/HotRepoCard.tsx
src/components/RepoList.tsx
src/components/SearchedRepoCard.tsx
src/hooks/useContributions.ts

Enabled the contributors avatars images in: Repository list cards, hot list cards & search cards. Also refractored search results into its own card component.
closes #333

feat: display repos' contributors avatars

---

src/App.tsx
src/components/ListRepositories.tsx
src/components/RecentRepoListWrap.tsx
src/components/RepoListWrap.tsx
src/components/SecondaryNav.tsx
src/components/VotedRepoListWrap.tsx

In "My Votes" repo list, organizes it by weeks, specifically organizes it by This Week, Last Week & Older.
closes #198

feat: organize voted repo list by week

---

src/App.tsx
src/components/ListRepositories.tsx
src/components/RecentRepoListWrap.tsx
src/components/RepoListWrap.tsx
src/components/VotedRepoListWrap.tsx

This puts a placeholder or an indication text in My Votes category when there are no voted repositories. This is instead of the empty list that was being displayed.
Other side fixes: Properly show skeletons for categories that are still loading (except Recent category)
closes #208

feat: Myvotes placeholder

---

src/components/RecentRepoListWrap.tsx
src/vite-types.d.ts

Sort repos in each list in recent category by user votes.
closes #399

feat: Sort recent repos by votes

---

src/lib/handleVoteUpdateByRepo.ts

fix: typo in handleVoteUpdateByRepo.ts

---

src/components/HotRepositories.tsx

feat: Update HotRepositories repos

---

README.md

Fixed a typo and a broken link on README.md
(prettier also fixed some whitespaces/empty lines, I'd keep the change)
Before
After

docs(readme): fix typo and unformatted link

---

src/components/Footer.tsx

This PR closes #453 by updating the status `href` in the footer.
Fixes #453 
No visual changes.

fix: Updated the status URL in the footer

---

.github/workflows/triage.yml

The take action was broken due to these updates
https://github.com/bdougie/take-action/releases/tag/v1.5
Removing the reusable workflow, since the open-sauced/open-sauced repo is going to be deprecated (no more onegraph) starting Wednesday.

fix: triage.yml

---

src/components/Footer.tsx

Refers to issue #455 
This PR tries to automatically update the year of the copyright section based on the current year

fix: make year dynamic in footer

---

.github/workflows/codeql-analysis.yml
.github/workflows/compliance.yml

We need to remove the open-sauced/open-sauced workflows and archive that repo.
This PR updates the CodeQL and Compliance workflows to be local. 
The CodeQL workflow now includes a matrix strategy for analyzing JavaScript code, while the Compliance workflow includes new checks for protected branches and issue references. Additionally, a new Welcome workflow has been added to greet first-time contributors with a message and an invitation to join the Open Sauced Discord community.
_Generated using [OpenSauced](https://opensauced.ai/)._
https://github.com/open-sauced/open-sauced/issues/1491

feat: Remove open-sauced/open-sauced workflows

---

src/components/HotRepositories.tsx

fix: update repo to open-sauced/app

---

npm-shrinkwrap.json
package.json
playwright.config.ts
vite.config.ts

Revolves https://github.com/aidenybai/million/issues/554
/claim https://github.com/aidenybai/million/issues/554
Closes #486

feat: add million.js

---

.github/workflows/triage.yml

Fixes #497
Relates to https://github.com/open-sauced/app/pull/1949

chore: updated triage workflow

---

.env

This upgrades the API to use the new incoming v2 API
Closes: https://github.com/open-sauced/hot/issues/508

feat: Upgrade to v2 API
