- src/components/PostGrid.jsx
- src/components/PostList.jsx
This PR adds the feature of redirecting you from the contributor's avatar that you clicked to their respective GitHub profile. This feature was added to the PostGrid and PostList JSX files
Fixes #29
> fix: avatar redirects to GitHub profile

- src/components/PostList.jsx
- src/components/PostsWrap.jsx
This PR fixes the bug that shows up on mobile view when you switch from grid view to list view. The cards start to overflow out of the screen and it makes it look weird. I have made the necessary correction and everything looks fine now
Fixes #53 
Screenshot of what my change looks like
> fix: PostList overlapping view correction

- README.md
This PR fixes the dependabot badge not loading in the README file. 
Fixes #98
> fix: badge not loading in README

- src/components/GridDisplay.tsx
This PR fixes #128 by adding a min-height to the load more button when it is the only item on a new row
fixes #128
Just a double check to make sure everything is good in production
> fix: add a min-height to the load more button to match the card height

- src/components/Hero.tsx
- src/components/HotRepositories.tsx
- src/components/PostList.tsx
- src/components/StackedAvatar.tsx
This PR replaces duplicate codes with one reusable one.
closes #287 
[#287 ](uhttps://github.com/open-sauced/hot/issues/287#issue-1327815977)
> feat: Made the contributors StackedAvatars component reusable

- vite.config.ts
The bug still seems to be present in my local host, but pushing for extras eyes on my code.
fix #243
This PR fixes the font loading bug. 
Fixes #243 
I don't see a change in my local host 😅
No I don't believe so.
I know I'm completely supported and standing in like 5 inches of water, and yet... Life as a junior dev I suppose lol
> fix(vite.config.ts): fix font loading bug

- src/components/SecondaryNav.tsx
Deleted flex-col and sm:flex-row in CSS for the subnav in mobile view as opposed to adding code.
Replaced with only flex-row for the subnav to display horizontally in mobile view.
fix #221
> feat: updated CSS to respect row in subnav

- src/components/StackedAvatar.tsx
Corrects tailwind classes not to use one-off width/height styles.
Following https://tailwindcss.com/docs/width for reference.
Fixes #318 
Before:
After:
> fix: correct tailwind antipattern

- src/App.tsx
this PR adds localStorage as a Context provider. It works as expected and caches data to prevent refetching the same content from the API on reload. 
fix #335
> feat: adds localstorageprovider

- src/App.tsx
- src/components/GridDisplay.tsx
- src/components/ListRepositories.tsx
- src/components/PrimaryNav.tsx
- src/components/RepoGrid.tsx
- src/components/RepoList.tsx
- src/components/RepoWrap.tsx
Adding an option at the drop down menu for the user to generate the bearer token on the console.
fix #364
> fix: Menu drop to generate token on console.

- src/components/ListRepositories.tsx
This PR adds 5 loading skeleton for the `repoWrap` component
Fixes #357
> feat: add loading skeleton for the repoWrap component

- src/components/Footer.tsx
- src/components/PrimaryNav.tsx
Fixes #426
I wasn't sure what style change for the _Sign In_ button would be best. Adding the text shadow meant I didn't need to add any new colors to the palette. In theory any change that increases color contrast just a bit could work, such as:
* Using a different (darker) orange
* Using a different color combo altogether
<table>
<thead>
<tr>
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
No(t yet). I'd love to add aXe in e2e tests but see the infra is actively being worked on in #403 -> #422
> fix: header and footer accessibility fixes: color contrast and image titles

- src/components/Footer.tsx
Uses `aria-label` instead of `title` on footer SVGs per https://html.spec.whatwg.org/multipage/dom.html#the-title-attribute.
* #426 -> #427
* https://twitter.com/hi__mayank/status/1602732880400158720
> fix: use aria-label instead of title for footer icons

- src/components/PrimaryNav.tsx
- src/components/RepoSubmission.tsx
- src/components/SecondaryNav.tsx
- src/components/StarTheRepo.tsx
- src/hooks/useSupabaseAuth.ts
- src/hooks/useVotedRepos.ts
- src/lib/githubAPI.ts
Uses the user's supabase provider (GitHub) token to check whether they've starred the repo using the [GitHub "Starring" REST API](https://docs.github.com/en/rest/activity/starring?apiVersion=2022-11-28#check-if-a-repository-is-starred-by-the-authenticated-user).
If they have, the header shows a filled star with _Starred on GitHub_ instead of an outline star with _Star us on GitHub_.
Because this switch takes place asynchronously, hides the messaging for pending logged-in users with a 200ms opacity transition to fade in.
Starts on #358.
Note: this doesn't add logic to `PUT` the user's star preference there. I'm getting 404s when I try and wanted to get this PR in for now. Is this ok for now?
https://user-images.githubusercontent.com/3335181/209575166-9c92c5b6-aabc-4d14-9ccb-a6d953f36e3f.mov …
> feat: check whether repo is starred for nav UI

- src/components/SecondaryNav.tsx
This PR fixes the secondary menu bug in mobile view where the last menu item, while signed-in, had unexpected wrapping behaviour. Flex-wrap added to allow multiline on smaller screens. 
Fixes #438 
Before: 
https://user-images.githubusercontent.com/43274289/210938781-5654a34a-919c-4ac6-805c-cabc358d42d8.mp4
After:
https://user-images.githubusercontent.com/43274289/210939322-a2cd4d3e-acc0-47e7-8f19-83e872817aca.mp4
> fix: mobile view secondary nav so it wraps on two lines when extra menu item added when signed in

- npm-shrinkwrap.json
- package.json
This PR bumps `node-emoji` to v2.
Fixes #466.
Apologies for not waiting till it was approved 😄 
Before & after this change, showing emojis works:
Not that I can think of.
> build: bump node-emoji to 2

- src/components/Hero.tsx
Icons in the input field of the hero section in the [page](https://hot.opensauced.pizza/) could be aligned with a simple flex and modifying tailwind-css at line 76 and adding an extra div at line 77;
Fixes #473 
Before:
After:
> fix: Styled input field

- src/components/ListRepositories.tsx
- src/components/RecentRepoListWrap.tsx
- src/components/RepoListWrap.tsx
- src/components/VotedRepoListWrap.tsx
- src/hooks/useRepositoriesList.ts
- src/hooks/useVotedRepositoriesList.ts
This PR fixes the load more button visibility issue  and now loads data upon clicking
Fixes #446 
Before :
[before.webm](https://github.com/open-sauced/hot/assets/25549935/a2081cde-28d1-402b-a8ec-94e12a861a20)
After :
[after.webm](https://github.com/open-sauced/hot/assets/25549935/4a1ce225-298a-40ac-88aa-7db772a22384)
:smiley:
> fix: Load more button visibility issue  and now loads data upon clicking

- src/components/Hero.tsx
- src/lib/github.ts
We have work in progress for new repo pages. I am preemptively updating the links to match this update. These links will 404.
https://github.com/open-sauced/app/issues/2961
Click any link on the home page.
> feat: update links to use app

- src/components/PrimaryNav.tsx
This PR replaces the `Print auth token` item in navbar with `Copy auth token`
Fixes #513 
Docs https://github.com/open-sauced/docs/pull/280
> feat: Replaced print auth token with copy to clipboard

- .eslintrc.cjs
- src/components/HotRepoCard.tsx
- src/lib/github.ts
Instead of taking users to GitHub, I am making the swap to use OpenSauced as the link.
> feat: Use OpenSauced links instead of GitHub
